import { combineReducers } from "redux";
import {
    postsSlice,
    catsSlice,
    eventsSlice,
    timelinesSlice,
    progressbarsSlice,
    progressbarListsSlice,
    productsSlice,
    usersSlice,
    aboutsSlice,
    testimonialsSlice,
    clientsSlice,
    socialsSlice,
    tabMenuesSlice,
    resumesSlice,
    clientSectionsSlice,
    pricingsSlice,
} from './adminSlices';

export default combineReducers({
    [postsSlice.name]: postsSlice.reducer,
    [catsSlice.name]: catsSlice.reducer,
    [eventsSlice.name]: eventsSlice.reducer,
    [timelinesSlice.name]: timelinesSlice.reducer,
    [progressbarsSlice.name]: progressbarsSlice.reducer,
    [progressbarListsSlice.name]: progressbarListsSlice.reducer,
    [productsSlice.name]: productsSlice.reducer,
    [usersSlice.name]: usersSlice.reducer,
    [aboutsSlice.name]: aboutsSlice.reducer,
    [testimonialsSlice.name]: testimonialsSlice.reducer,
    [clientsSlice.name]: clientsSlice.reducer,
    [socialsSlice.name]: socialsSlice.reducer,
    [tabMenuesSlice.name]: tabMenuesSlice.reducer,
    [resumesSlice.name]: resumesSlice.reducer,
    [clientSectionsSlice.name]: clientSectionsSlice.reducer,
    [pricingsSlice.name]: pricingsSlice.reducer,
})